name: uptime
services:
  uptime:
    image: louislam/uptime-kuma:beta
    volumes:
      - uptime-data:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.services.uptime.loadbalancer.server.port=3001
      - traefik.http.routers.uptime.rule=Host(`${HOST?}`)
      - traefik.http.routers.uptime.tls.certresolver=le
    networks:
      - default
      - traefik

  mysql:
    image: mysql:9
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uptime
      MYSQL_USER: uptime
      MYSQL_PASSWORD: uptime

volumes:
  uptime-data:
  mysql-data:

networks:
  traefik:
    name: traefik
