server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /promtail/positions/positions.yaml

clients:
  - url: '${LOKI_ORIGIN}/loki/api/v1/push'

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - target_label: job
        replacement: docker
      - target_label: 'host'
        replacement: '${PROMTAIL_LABEL_HOST}'
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
