name: traefik
services:
  traefik:
    image: traefik:3.3
    command:
      - --accesslog
      - --metrics.prometheus=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=http
      - --certificatesresolvers.le.acme.email=le@sikademo.com
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    userns_mode: host
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik.rule=Host(`${HOST?}`)
      - traefik.http.routers.traefik.tls.certresolver=le

volumes:
  letsencrypt:

networks:
  traefik:
    name: traefik
