global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 127.0.0.1:9090
  - job_name: docker
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: trafik
    static_configs:
      - targets:
        - traefik:8080
